INSERT INTO public.access_control (email, folder) VALUES ('viveks@samanvayfoundation.org', '1. FES Rajasthan');
INSERT INTO public.access_control (email, folder) VALUES ('viveks@samanvayfoundation.org', '2. NREGA Mandya');
INSERT INTO public.access_control (email, folder) VALUES ('viveks@samanvayfoundation.org', '3. FES Karnataka');
INSERT INTO public.access_control (email, folder) VALUES ('viveks@samanvayfoundation.org', '4. Vrutti');
INSERT INTO public.access_control (email, folder) VALUES ('viveks@samanvayfoundation.org', '5. FES Odisha');
INSERT INTO public.access_control (email, folder) VALUES ('soumya@catalysts.org', '1. FES Rajasthan');
INSERT INTO public.access_control (email, folder) VALUES ('soumya@catalysts.org', '2. NREGA Mandya');
INSERT INTO public.access_control (email, folder) VALUES ('soumya@catalysts.org', '3. FES Karnataka');
INSERT INTO public.access_control (email, folder) VALUES ('soumya@catalysts.org', '4. Vrutti');
INSERT INTO public.access_control (email, folder) VALUES ('soumya@catalysts.org', '5. FES Odisha');
